name: installation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install-procedure:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup git config
        run: |
          # From: https://lannonbr.com/blog/2019-12-09-git-commit-in-actions
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Install required packages
        run:  sudo apt install -y dar dar-static  par2

      - name: run install steps
        run: |
          chmod +x $GITHUB_WORKSPACE/test/test-install-package.sh
          $GITHUB_WORKSPACE/test/test-install-package.sh
