name: linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install required packages
        run:  sudo apt install -y shellcheck

      - name: Run linter
        run: |
          chmod +x $GITHUB_WORKSPACE/test/test-shellcheck.sh
          $GITHUB_WORKSPACE/test/test-shellcheck.sh
