name: Update PyPI Downloads
permissions:
  contents: read
  pull-requests: write
  
on:
  schedule:
# 3:15 UTC according to https://docs.github.com/en/actions/use-cases-and-examples/project-management/scheduling-issue-creation 
    - cron: '15 3 * * *'  # approx 2 hours after PyPI stats should finish
  workflow_dispatch:       # Allow manual runs

jobs:
  update-downloads:
    
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push changes to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log current UTC time
        run: |
          echo Time of workflow run:
          date -u
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pypistats

      - name: Run download tracker
        run: python track_downloads.py

      - name: Verify changes
        run: |
          unauthorized_files=$(git diff --name-only | grep -vE "^(downloads\.json|README\.md)$" || true)
          if [[ -n "$unauthorized_files" ]]; then
            echo "Unauthorized file modification detected in:"
            echo "$unauthorized_files"
            exit 1
          fi
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add downloads.json
          git commit -m 'chore: update total downloads' || echo "No changes to commit"
          git push




